#!/bin/sh

cd weixiao-master

txt=.txt
json=.json
defaultname=items
outputpath=../data/spider/

current_time=$(date "+%s_%N")
#echo "Current Time : $current_time"

txtfile=$defaultname.$current_time$txt
jsonfile=$outputpath$defaultname.$current_time$json

#scrapy crawl weixiao -o $txtfile -t json
scrapy crawl weixiao
#mv $txtfile $jsonfile

#rm $jsonfile

cd ..
